"""Generate the carpet_diagram_<period>.ipynb benchmarking notebooks via nbformat.

The script is the source of truth — edit it, not the generated `.ipynb` files,
then regenerate and execute:

    python build_notebook.py        # writes carpet_diagram_<period>.ipynb for each period
    jupyter nbconvert --to notebook --execute --inplace carpet_diagram_lig127k.ipynb
    jupyter nbconvert --to notebook --execute --inplace carpet_diagram_midHolocene.ipynb

Every period shares the same Steps 2–4 (model anomalies, sampling, RMSE); only the
reconstruction parsing in Step 1 differs, because each compilation ships its proxy
table in its own layout. Each period is described by a PERIOD config below.
"""
import os
import nbformat as nbf


# --------------------------------------------------------------------------- #
# Period-specific Step 1 — reconstruction parsing.
#
# Each Step 1 cell must build a DataFrame `recon` with the columns
#   compilation, reference, site, Proxy, Latitude, Longitude, Anom
# and write it to output/recon_points_<EXPERIMENT>.csv.  Everything downstream
# (Steps 2–4) is identical across periods and is generated by build().
# --------------------------------------------------------------------------- #

LIG127K_STEP1_MD = """## Step 1 — Reconstruction compilations

The three CSVs from the Otto-Bliesner et al. (2021) supplement (Tables S2–S4) split the
proxies by region and have slightly different column layouts, but all share
`Compilation reference`, `Latitude`, `Longitude` and `Anom` (the central annual-mean
temperature anomaly estimate). We normalise them and split into the two compilations,
**Hoffman** (global SST) and **Capron** (high-latitude)."""

LIG127K_STEP1_CODE = """recon_files = sorted(glob.glob(os.path.join(RECON_DIR, 'mat_*.csv')))
assert recon_files, 'no reconstruction CSVs found'

frames = []
for f in recon_files:
    df = pd.read_csv(f, header=2)
    site_col = 'Site Name' if 'Site Name' in df.columns else 'Core'
    sub = df[['Compilation reference', site_col, 'Latitude', 'Longitude', 'Proxy', 'Anom']].copy()
    sub = sub.rename(columns={'Compilation reference': 'reference', site_col: 'site'})
    sub['source_table'] = os.path.basename(f)
    frames.append(sub)

recon = pd.concat(frames, ignore_index=True)
# Keep only rows with a usable location and anomaly
recon = recon.dropna(subset=['Latitude', 'Longitude', 'Anom'])
recon[['Latitude', 'Longitude', 'Anom']] = recon[['Latitude', 'Longitude', 'Anom']].astype(float)

# Two compilations: Hoffman and Capron
recon['compilation'] = np.where(recon['reference'].str.contains('Hoffman', case=False),
                                'Hoffman',
                                np.where(recon['reference'].str.contains('Capron', case=False),
                                         'Capron', 'other'))
assert (recon['compilation'] != 'other').all(), recon.loc[recon.compilation=='other','reference'].unique()

print(recon.groupby('compilation').size())
recon_out = os.path.join(OUT_DIR, f'recon_points_{EXPERIMENT}.csv')
recon.to_csv(recon_out, index=False)
print('wrote', recon_out)
recon.head()"""


MIDHOL_STEP1_MD = """## Step 1 — Reconstruction compilations

Two midHolocene (6 ka) compilations, each in its own CSV with a plain header row:

- **Bartlein** — the Bartlein et al. (2011) pollen-based mean-annual-temperature (MAT)
  anomalies; the annual anomaly is the `mat_anm_mean` column.
- **Temp12k** — the Temp12k database extraction (Kaufman et al. 2020; described in
  Brierley et al. 2020); the annual anomaly is the `anom` column.

Both store latitude/longitude as plain `lat`/`lon` columns (longitudes −180–180°). We
normalise them to the shared `compilation, reference, site, Proxy, Latitude, Longitude,
Anom` schema used by the rest of the pipeline."""

MIDHOL_STEP1_CODE = """# (compilation, filename, anomaly column, reference label, proxy label)
recon_specs = [
    ('Bartlein', 'Bartlein_mat.csv',       'mat_anm_mean', 'Bartlein et al. 2011',                  'pollen MAT'),
    ('Temp12k',  'temp12k_anom6k_mat.csv', 'anom',         'Temp12k (Kaufman et al. 2020)',         'multiproxy'),
]

frames = []
for comp, fname, anom_col, ref, proxy in recon_specs:
    df = pd.read_csv(os.path.join(RECON_DIR, fname))
    df.columns = [c.strip() for c in df.columns]  # some Bartlein headers carry leading spaces
    sub = pd.DataFrame({
        'compilation': comp,
        'reference': ref,
        'site': np.nan,          # these gridded compilations carry no site names
        'Proxy': proxy,
        'Latitude': df['lat'].astype(float),
        'Longitude': df['lon'].astype(float),
        'Anom': df[anom_col].astype(float),
    })
    sub['source_table'] = fname
    frames.append(sub)

recon = pd.concat(frames, ignore_index=True)
recon = recon.dropna(subset=['Latitude', 'Longitude', 'Anom'])

print(recon.groupby('compilation').size())
recon_out = os.path.join(OUT_DIR, f'recon_points_{EXPERIMENT}.csv')
recon.to_csv(recon_out, index=False)
print('wrote', recon_out)
recon.head()"""


LGM_STEP1_MD = """## Step 1 — Reconstruction compilations

Two LGM (21 ka) compilations, both near-global gridded anomaly products (so each point
gets a `cos(latitude)` weight for an area-fair RMSE):

- **Cleator** — the Cleator et al. (2020) vegetation-model-inversion data assimilation.
  A long metadata preamble precedes a `#`-prefixed header row (line 77); the only relevant
  field is `MAT` (mean-annual-temperature anomaly, °C) at each land grid cell.
- **Osman** — the Last Glacial Maximum Reanalysis (Osman et al. 2021), the ensemble-mean
  `sat` field from `Osman_LGMR_21ka_SAT_anom_climo.nc`, already differenced to a 21 ka −
  (0–1 ka) anomaly. The 96×144 grid is flattened to points, dropping fill values."""

LGM_STEP1_CODE = """# --- Cleator: gridded land MAT anomalies from a CSV with a preamble ---
CLE_COLS = ['lat', 'lon', 'MI', 'MAP', 'MAT', 'MTCO', 'MTWA', 'GDD5',
            'MI_SD', 'MAP_SD', 'MAT_SD', 'MTCO_SD', 'MTWA_SD', 'GDD5_SD']
cle = pd.read_csv(os.path.join(RECON_DIR, 'cleator2020_recon.csv'),
                  skiprows=77, header=None, names=CLE_COLS)
cle = cle.apply(pd.to_numeric, errors='coerce').dropna(subset=['lat', 'lon', 'MAT'])
cleator = pd.DataFrame({
    'compilation': 'Cleator', 'reference': 'Cleator et al. 2020', 'site': np.nan,
    'Proxy': 'pollen MAT (assim.)',
    'Latitude': cle['lat'].astype(float), 'Longitude': cle['lon'].astype(float),
    'Anom': cle['MAT'].astype(float),
})
cleator['source_table'] = 'cleator2020_recon.csv'

# --- Osman: flatten the gridded LGMR SAT anomaly field to points ---
ds = xr.open_dataset(os.path.join(RECON_DIR, 'Osman_LGMR_21ka_SAT_anom_climo.nc'),
                     decode_times=False)
sat = ds['sat'].where(np.abs(ds['sat']) < 1e30)
lon2d, lat2d = np.meshgrid(sat['lon'].values, sat['lat'].values)
osman = pd.DataFrame({
    'compilation': 'Osman', 'reference': 'Osman et al. 2021', 'site': np.nan,
    'Proxy': 'LGMR SAT (assim.)',
    'Latitude': lat2d.ravel().astype(float), 'Longitude': lon2d.ravel().astype(float),
    'Anom': sat.values.ravel().astype(float),
})
osman['source_table'] = 'Osman_LGMR_21ka_SAT_anom_climo.nc'

recon = pd.concat([cleator, osman], ignore_index=True)
recon = recon.dropna(subset=['Latitude', 'Longitude', 'Anom'])
# Both are regular lat/lon grids: cos-latitude weight makes the RMSE area-fair.
recon['weight'] = np.cos(np.deg2rad(recon['Latitude']))

print(recon.groupby('compilation').size())
recon_out = os.path.join(OUT_DIR, f'recon_points_{EXPERIMENT}.csv')
recon.to_csv(recon_out, index=False)
print('wrote', recon_out)
recon.head()"""


MIDPLIO_STEP1_MD = """## Step 1 — Reconstruction compilation

One midPliocene (mid-Piacenzian, ~3.2 Ma; eoi400 boundary conditions) compilation:

- **Foley-Dowsett** — the Foley & Dowsett (2019) alkenone (Uk'37) sea-surface-temperature
  sites, as used by Haywood et al. (2020). The file carries two anomaly columns; following
  Haywood et al. we use the **NOAA ERSST5** anomaly (SST minus the NOAA ERSST5 modern
  climatology), which is the last, unnamed column (`Unnamed: 14`)."""

MIDPLIO_STEP1_CODE = """df = pd.read_csv(os.path.join(RECON_DIR,
                 'FoleyDowsett2019_cs_mp_sst_data_30k_plus_NOAA.csv'))
# The trailing unnamed column is SST minus the NOAA ERSST5 modern climatology.
anom_col = 'Unnamed: 14'
recon = pd.DataFrame({
    'compilation': 'Foley-Dowsett', 'reference': 'Foley & Dowsett 2019',
    'site': df['Location or site'].astype(str).str.strip(),
    'Proxy': "Uk'37 SST",
    'Latitude': df['Latitude'].astype(float), 'Longitude': df['Longitude'].astype(float),
    'Anom': df[anom_col].astype(float),
})
recon['source_table'] = 'FoleyDowsett2019_cs_mp_sst_data_30k_plus_NOAA.csv'
recon = recon.dropna(subset=['Latitude', 'Longitude', 'Anom'])

print(recon.groupby('compilation').size())
recon_out = os.path.join(OUT_DIR, f'recon_points_{EXPERIMENT}.csv')
recon.to_csv(recon_out, index=False)
print('wrote', recon_out)
recon.head()"""


PERIODS = [
    dict(
        experiment='midPliocene-eoi400',
        long_name='mid-Pliocene warm period (~3.2 Ma, eoi400)',
        compilations='Foley-Dowsett SST (Foley & Dowsett 2019; Haywood et al. 2020)',
        step1_md=MIDPLIO_STEP1_MD,
        step1_code=MIDPLIO_STEP1_CODE,
    ),
    dict(
        experiment='lgm',
        long_name='Last Glacial Maximum (21 ka)',
        compilations='Cleator (Cleator et al. 2020) and Osman (LGMR; Osman et al. 2021)',
        step1_md=LGM_STEP1_MD,
        step1_code=LGM_STEP1_CODE,
    ),
    dict(
        experiment='lig127k',
        long_name='Last Interglacial (127 ka)',
        compilations='Hoffman and Capron (Otto-Bliesner et al. 2021)',
        step1_md=LIG127K_STEP1_MD,
        step1_code=LIG127K_STEP1_CODE,
    ),
    dict(
        experiment='midHolocene',
        long_name='mid-Holocene (6 ka)',
        compilations='Bartlein (Bartlein et al. 2011) and Temp12k (Kaufman et al. 2020)',
        step1_md=MIDHOL_STEP1_MD,
        step1_code=MIDHOL_STEP1_CODE,
    ),
]


def build(period):
    """Assemble and write carpet_diagram_<experiment>.ipynb for one period."""
    nb = nbf.v4.new_notebook()
    cells = []
    md = lambda s: cells.append(nbf.v4.new_markdown_cell(s))
    co = lambda s: cells.append(nbf.v4.new_code_cell(s))

    exp = period['experiment']

    md(f"""# Carpet diagram — {exp} temperature benchmarking

Step toward an update of IPCC AR5 WG1 Fig. 9.12 (a *portrait plot* / *carpet
diagram*). For each PMIP {exp} ({period['long_name']}) simulation we:

1. Load the annual-mean near-surface temperature field `tas_spatialmean_ann` from the
   CVDP output, and the matching `piControl` run.
2. Compute the **{exp} − piControl anomaly** on each model's native grid.
3. **Sample** that anomaly field at the location of every proxy reconstruction.
4. Summarise the model–data mismatch as the **root-mean-squared error (RMSE)** against
   each reconstruction compilation ({period['compilations']}).

Intermediate tables are written to `output/`. Run with the `my-cli-py` conda env.""")

    co(f"""import os, glob, re
import numpy as np
import pandas as pd
import xarray as xr

ROOT      = os.getcwd()  # run the notebook from the carpet_diagram/ directory
CVDP_DIR  = os.path.join(ROOT, 'cvdp_output_by_experiment')
EXPERIMENT = '{exp}'
RECON_DIR = os.path.join(ROOT, 'recons', EXPERIMENT)
OUT_DIR   = os.path.join(ROOT, 'output')
os.makedirs(OUT_DIR, exist_ok=True)

VAR        = 'tas_spatialmean_ann'
print('experiment:', EXPERIMENT)
print('CVDP   :', CVDP_DIR)
print('recons :', RECON_DIR)
print('output :', OUT_DIR)""")

    # --- Step 1: period-specific reconstruction parsing ---
    md(period['step1_md'])
    co(period['step1_code'])

    # --- Step 2: model anomalies (shared) ---
    md(f"""## Step 2 — Model {exp} − piControl anomalies

Each model writes its CVDP field on its own native grid, so anomalies are computed
per model. We pair every `{exp}` file with the same model's `piControl` file
(ignoring the auxiliary `.monsoon.` / `.tas.indices.` files). If the two grids ever
differ, the control is bilinearly regridded onto the {exp} grid before differencing.""")

    co("""def model_files(experiment):
    \"\"\"Map model name -> path for the main CVDP file of an experiment.\"\"\"
    out = {}
    pat = os.path.join(CVDP_DIR, experiment, f'*_{experiment}.cvdp_data.*.nc')
    for f in sorted(glob.glob(pat)):
        b = os.path.basename(f)
        if '.monsoon.' in b or '.tas.indices.' in b or b.endswith('.tmp'):
            continue
        model = b.split(f'_{experiment}.cvdp_data')[0]
        out[model] = f  # last (sorted) wins; there is one main file per model
    return out

def has_var(path):
    \"\"\"True if the CVDP file actually carries the tas field (a few don't).\"\"\"
    with xr.open_dataset(path, decode_times=False) as ds:
        return VAR in ds.variables

exp_files = model_files(EXPERIMENT)
pi_files  = model_files('piControl')
paired = sorted(set(exp_files) & set(pi_files))
# Some CVDP files lack tas_spatialmean_ann entirely — drop those models.
models = [m for m in paired if has_var(exp_files[m]) and has_var(pi_files[m])]
print(f'{len(models)} models with both {EXPERIMENT} and piControl (and a tas field):')
print(models)
missing_pi = sorted(set(exp_files) - set(pi_files))
if missing_pi:
    print(f'{EXPERIMENT} models with no piControl (skipped):', missing_pi)
no_var = [m for m in paired if m not in models]
if no_var:
    print(f'models dropped — no {VAR} in CVDP file:', no_var)""")

    co("""def load_field(path):
    da = xr.open_dataset(path, decode_times=False)[VAR].sortby('lat').sortby('lon')
    # A few CVDP grids (e.g. LOVECLIM piControl) carry duplicate lon values,
    # which break interpolation; keep the first occurrence of each coordinate.
    for dim in ('lat', 'lon'):
        _, idx = np.unique(da[dim].values, return_index=True)
        if len(idx) != da.sizes[dim]:
            da = da.isel({dim: np.sort(idx)})
    return da

anomalies = {}
for m in models:
    exp_field = load_field(exp_files[m])
    pi  = load_field(pi_files[m])
    if exp_field.shape != pi.shape or not (np.allclose(exp_field.lat, pi.lat) and np.allclose(exp_field.lon, pi.lon)):
        pi = pi.interp(lat=exp_field.lat, lon=exp_field.lon)
    anomalies[m] = (exp_field - pi).rename('tas_anom')
    print(f'{m:18s} grid {exp_field.shape}  mean anom {float(anomalies[m].mean()):+.2f} C')""")

    # --- Step 3: sampling (shared) ---
    md("""## Step 3 — Sample model anomalies at reconstruction locations

Model longitudes run 0–360°, the proxy longitudes −180–180°, so targets are wrapped to
0–360 and the field is made cyclic in longitude before bilinear interpolation.

Each recon point carries a `weight` used later in the RMSE. Scattered-site compilations
weight every point equally (1.0); gridded near-global reconstructions (Cleator, Osman)
set `weight = cos(latitude)` so the RMSE is area-fair rather than pole-heavy.""")

    co("""def sample_points(field, lats, lons):
    \"\"\"Bilinearly sample a (lat, lon) field at scattered points; lon made cyclic.\"\"\"
    lon_cyc = np.append(field.lon.values, field.lon.values[0] + 360.0)
    fcyc = xr.concat([field, field.isel(lon=0)], dim='lon').assign_coords(lon=lon_cyc)
    ta = xr.DataArray(np.asarray(lats), dims='point')
    to = xr.DataArray(np.asarray(lons) % 360.0, dims='point')
    return fcyc.interp(lat=ta, lon=to).values

sampled = recon[['compilation', 'reference', 'site', 'Proxy',
                 'Latitude', 'Longitude', 'Anom']].copy()
sampled = sampled.rename(columns={'Anom': 'recon_anom'})
# Optional per-point weight (defaults to equal weighting when Step 1 omits it).
sampled['weight'] = recon['weight'].values if 'weight' in recon.columns else 1.0
for m in models:
    sampled[m] = sample_points(anomalies[m], sampled['Latitude'].values, sampled['Longitude'].values)

sampled_out = os.path.join(OUT_DIR, f'model_anom_at_recon_{EXPERIMENT}.csv')
sampled.to_csv(sampled_out, index=False)
print('wrote', sampled_out, '  shape', sampled.shape)
sampled.head()""")

    # --- Step 4: RMSE (shared) ---
    md("""## Step 4 — RMSE of each model against each compilation

For every model × compilation we take the model-minus-proxy difference across all proxy
points in that compilation and report the (weight-weighted) RMSE and bias, plus the number
of points contributing (a point off the model grid edge can return NaN). With unit weights
this is the ordinary RMSE; gridded compilations use `cos(latitude)` weights (Step 3).""")

    co("""records = []
for m in models:
    for comp, grp in sampled.groupby('compilation'):
        diff = grp[m].values - grp['recon_anom'].values
        w = grp['weight'].values
        valid = np.isfinite(diff) & np.isfinite(w)
        n = int(valid.sum())
        if n:
            dv, wv = diff[valid], w[valid]
            rmse = float(np.sqrt(np.sum(wv * dv ** 2) / np.sum(wv)))
            bias = float(np.sum(wv * dv) / np.sum(wv))
        else:
            rmse = bias = np.nan
        records.append({'model': m, 'compilation': comp, 'n_points': n,
                        'rmse': rmse, 'bias': bias})

rmse_long = pd.DataFrame(records)
rmse_wide = rmse_long.pivot(index='model', columns='compilation', values='rmse')
rmse_wide.columns = [f'{c}_RMSE' for c in rmse_wide.columns]

rmse_long.to_csv(os.path.join(OUT_DIR, f'rmse_long_{EXPERIMENT}.csv'), index=False)
rmse_wide.to_csv(os.path.join(OUT_DIR, f'rmse_summary_{EXPERIMENT}.csv'))
print(f'wrote rmse_long_{EXPERIMENT}.csv and rmse_summary_{EXPERIMENT}.csv')
rmse_wide.sort_values(rmse_wide.columns[0])""")

    md("""These RMSE values are the building blocks of the carpet diagram: one column per model,
one row per (period, reconstruction compilation), coloured by RMSE. `carpet_figure.py`
reads every `output/rmse_long_<period>.csv`, so re-running this notebook for a new period
makes its rows appear in the portrait plot automatically.""")

    nb['cells'] = cells
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       f'carpet_diagram_{exp}.ipynb')
    nbf.write(nb, out)
    print('wrote', out)


if __name__ == '__main__':
    for period in PERIODS:
        build(period)
